### PR TITLE
fix: allow delete method request to send data

### PR DESCRIPTION
**Pull request by BenjaminMINK**
Hello,

I think the `delete` method should be allowed to send data on `request` method

### CODE REVIEW

**Comment by wopian** [comment]
Can you add a test for this change in the delete.spec.js file?

**Review by wopian — CHANGES_REQUESTED** [review]
Can you add a test that sends a DELETE request with a body in the delete.spec.js file, so that this change is covered? You should be able to utilise one of the existing tests in POST or PATCH.

**Comment by BenjaminMINK** [comment]
> Can you add a test that sends a DELETE request with a body in the delete.spec.js file, so that this change is covered? You should be able to utilise one of the existing tests in POST or PATCH.

Okay, I'll add it

**Comment by BenjaminMINK** [comment]
Hello,

It seems we need more than just adding a single test: with the proposed modification, many tests fails because many are related to the `request` method which is not handling well different cases, especially in the `isValid` method called from `serialise` that we need to also handle the `DELETE` that can be either empty or filled...

**Comment by wopian** [comment]
I'll take a look into that in the coming week 👍

**Pull request closed without merging**
