### PR TITLE
Fix axios call signatures

### LINKED ISSUE #86: Wrong Content-Type in 4.1.0
I just upgraded from 3.1.4 to 4.1.0.

Here's how I initialize kitsu:

```js
<script>
const Kitsu = require('kitsu');

const api = new Kitsu({
    baseURL: '{{config['PREFERRED_URL_SCHEME']}}://{{config['SERVER_NAME']}}/api',
//    headers: {
//        Authorization: 'foobar'
//    }
});
api.headers['Authorization'] = 'foobar';
```

And here's how I make a request:

```js
        api.update('containers', {
            id: container_id,
            status: container_action
        }).then(function(res) {
            console.log(res);
        })
            .catch((reason) => console.log(reason));
```

My requests should be sent with `application/vnd.api+json` Content-Type, but they aren't, no matter what I do it is sent with `application/json;charset=utf-8` which happens to be the Axios default.

So I suspect that something broke between 3.x and 4.x that causes Axios to no longer set / see the correct Content-Type.

Here is the libs I am using:

```
├─ kitsu@4.1.0
│  ├─ axios@^0.17.0
│  ├─ babel-runtime@^6.26.0
│  └─ pluralize@^7.0.0
```

### PR DESCRIPTION
**Pull request by duk3luk3**
The axios api apparently changed and we weren't looking.

Headers are now passed to axios in separate "config" parameter dict
instead of in the "data" dict.

Fixes #86

### CODE REVIEW

**Comment by duk3luk3** [comment]
Caveat: Apparently we don't have any end-to-end testing that checks whether the xhr requests actually end up looking the way we want them to look, or they would have revealed this earlier.

So the tests passing on this doesn't mean it works.

**Comment by duk3luk3** [comment]
I just added a version of kitsu built from this PR's code to my app and it fixes the issue I was having.

**Comment by wopian** [comment]
Deduplicated the header assignments - this was already done a few lines above to check logged in status. However this didn't actually fix it from the tests I added for each method - `get`, `remove` and `self` were already passing in the tests before and this breaks all of the methods 😢 

Looked through the Axios documentation and the only methods that needed fixing were the `post` and `patch` methods with the `data` object taken out of the config (below). Doing this fixes the tests, so I've applied that on the master instead of this PR

Can you check the latest master (https://github.com/wopian/kitsu/commit/ff2d0d075b94ad9837c5baeae32832900cda6299) works and confirm there isn't an issue with the mocked Axios getting its behaviour changed?

```
axios#get(url[, config])
axios#delete(url[, config])
axios#post(url[, data[, config]])
axios#patch(url[, data[, config]])
```

**Comment by duk3luk3** [comment]
Nope, https://github.com/wopian/kitsu/commit/ff2d0d075b94ad9837c5baeae32832900cda6299 doesn't work - it doesn't wrap the data in `{ data: ... }` anymore which it needs to do - you forgot to wrap it in braces, this:

```
(await serialise.apply(this, [ model, body, 'PATCH' ])).data,
```

needs to be like this I think:

```
{ (await serialise.apply(this, [ model, body, 'PATCH' ])).data },
```

**Comment by wopian** [comment]
OK, should be fixed now - forgot to remove the (hacky) deduplication of `data` when removing the cause of it in that change 😭 

Should have changed it to:
```js
await serialise.apply(this, [ model, body, 'PATCH' ]),
```

Also added tests that check the data contents of the request, so this will be caught in the future.

**Comment by duk3luk3** [comment]
yup, master seems to work fine now

**Comment by wopian** [comment]
Awesome - will release `4.2.0`

**Pull request closed without merging**
