### PR TITLE
Fix types issue

### LINKED ISSUE #967: Issue with types
Encountering this issue in vscode for one of my tests

```
Could not find a declaration file for module 'kitsu'. 'node_modules/kitsu/dist/index.mjs' implicitly has an 'any' type.
There are types at 'node_modules/kitsu/types/index.d.ts', but this result could not be resolved when respecting package.json "exports".
The 'kitsu' library may need to update its package.json or typings.ts(7016)
```

### PR DESCRIPTION
**Pull request by justin-tay**
Closes #967

### CODE REVIEW

**Comment by wopian** [comment]
Does this need to be added for all the exports?

**Review by wopian — APPROVED** [review]

**Comment by wopian** [comment]
Thank you! A new release will be cut later today.

**Comment by tompato** [comment]
Sorry to resurrect this, but could we get a release for this fix? :)

**Comment by wopian** [comment]
Apologies for the delay. This has been released as 10.1.4 including the same change applied to the `kitsu-core` exports.

Please note that the repository had a force-push to amend the PR title to conform to our commit naming scheme (to be tracked as a change in changelog and version picking)

Changelog: https://github.com/wopian/kitsu/releases/tag/v10.1.4

**Pull request merged**
