### PR TITLE
Adding sub relationships for routes with 4 subpaths

### PR DESCRIPTION
**Pull request by koji98**
An example of this is [https://kitsu.io/api/edge/media-relationships/10743/relationships/destination](https://kitsu.io/api/edge/media-relationships/10743/relationships/destination)

### CODE REVIEW

**Comment by koji98** [comment]
It says that I'm failing the code climate check? Not sure how to resolve this? @wopian

**Comment by wopian** [comment]
> It says that I'm failing the code climate check? Not sure how to resolve this?

Can you re-open this pull request on a new branch instead of the default branch? Looks like Code Climate is having some issues checking out your master branch.

```
git checkout -b subroutes
git push -u origin subroutes
```

**Comment by wopian** [comment]
Additionally, can you rebase your fork - you can do it via GitHub itself now as shown below:

image

I do not have write-access to your fork, so can't do it myself

**Comment by koji98** [comment]
Ok, I've done as you requested (rebased and made PR on a different branch). I'm closing this PR now.

**Pull request closed without merging**
